apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DB_HOST
            - name: DB_NAME
            - name: DB_PASSWORD
            - name: DB_USERNAME
          image: app
          name: app
          ports:
            - containerPort: 6673
              protocol: TCP
          volumeMounts:
            - mountPath: /app/node_modules
              name: packagevolume
      restartPolicy: Always
      volumes:
        - name: packagevolume
          persistentVolumeClaim:
            claimName: packagevolume
