
services:
  app:
    build: 
      context: .
      dockerfile: AppDockerfile
    container_name: spacex
    ports:
      - "6673:6673"
    volumes:
      - packagevolume:/app/node_modules
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
      cache:
        condition: service_healthy
    environment:
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - SPACEX_REDIS=$SPACEX_REDIS
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "localhost:6673/v4/admin/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  cache:
    image: "redis:7.4"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo:
    image: "mongo:6.0"
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - mongodata:/data/db
      - ./dump/spacex.2024-7-5.agz:/spacex.2024-7-5.agz
    environment:
      - MONGO_INITDB_DATABASE=$DB_NAME
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 15s
      retries: 3
    networks:
      - app-network

volumes:
  packagevolume:
  mongodata:

networks:
  app-network:
    driver: bridge
