apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: packagevolume
  name: packagevolume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
